language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.7.*" PHPUNIT_BRIDGE=true

matrix:
  include:
      # cannot be tested with 2.0 due to lack of compatible doctrine/doctrine-bundle version
    - env: SYMFONY_VERSION="2.1.*"
    - env: SYMFONY_VERSION="2.2.*"
    - env: SYMFONY_VERSION="2.3.*"
    - env: SYMFONY_VERSION="2.4.*"
    - env: SYMFONY_VERSION="2.5.*"
    - env: SYMFONY_VERSION="2.6.*"
    - env: SYMFONY_VERSION="2.8.*" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
    - env: SYMFONY_VERSION="dev-master" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
  allow_failures:
    - php: 7.0
    - php: hhvm
    - env: SYMFONY_VERSION="2.8.*" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
    - env: SYMFONY_VERSION="dev-master" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
  fast_finish: true

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update --dev
  - composer install --prefer-source
  - mysql -e "create database IF NOT EXISTS test;" -uroot

script:
  - phpunit --colors --verbose
