language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql --user="travis" --password="" test <./Tests/config/schema.sql

script:
  - phpunit --coverage-text --colors --verbose
