language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source
  - php app/console doctrine:fixtures:load

script:
  - phpunit --coverage-text --colors --verbose
